// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCThibdQlziIE70rTXU8BhveRAHQWJeq_g',
    appId: '1:856757854744:web:56dc778d210b57a5f0596d',
    messagingSenderId: '856757854744',
    projectId: 'bayarm',
    authDomain: 'bayarm.firebaseapp.com',
    storageBucket: 'bayarm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsim65Wxm40UI0OhMH7qu96CJWEhHNfjI',
    appId: '1:856757854744:android:b82613f85b5cca50f0596d',
    messagingSenderId: '856757854744',
    projectId: 'bayarm',
    storageBucket: 'bayarm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz3GSzyzZRtL9NWf8xvjPh_kSuOk171mo',
    appId: '1:856757854744:ios:eb2e6fd6ee94b976f0596d',
    messagingSenderId: '856757854744',
    projectId: 'bayarm',
    storageBucket: 'bayarm.appspot.com',
    iosClientId: '856757854744-1qaa8ode31agqc2t8po0p6f7m75h386s.apps.googleusercontent.com',
    iosBundleId: 'com.example.bayarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz3GSzyzZRtL9NWf8xvjPh_kSuOk171mo',
    appId: '1:856757854744:ios:eb2e6fd6ee94b976f0596d',
    messagingSenderId: '856757854744',
    projectId: 'bayarm',
    storageBucket: 'bayarm.appspot.com',
    iosClientId: '856757854744-1qaa8ode31agqc2t8po0p6f7m75h386s.apps.googleusercontent.com',
    iosBundleId: 'com.example.bayarm',
  );
}
